[package]
name = "DataPreprocessor"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["blocking"] }
scraper = "0.12"
quick-xml = { version = "0.23", features = ["serialize"] }
serde = { version = "1.0", features = ["derive"] }
csv = "1.1"